// models/BbpsTransaction.js
import { DataTypes } from "sequelize";

export default (sequelize) => {
  const BbpsTransaction = sequelize.define("BbpsTransaction", {
    orderId: { type: DataTypes.STRING },
    transactionId: { type: DataTypes.STRING },
    ntarTransactionId: { type: DataTypes.STRING },
    serviceName: { type: DataTypes.STRING },
    referenceId: { type: DataTypes.STRING },
    payInStatus: { type: DataTypes.STRING },
    operator: { type: DataTypes.STRING },
    subService: { type: DataTypes.STRING },
    amount: { type: DataTypes.FLOAT },
    amountInPaisa: { type: DataTypes.FLOAT },
    userName: { type: DataTypes.STRING },
    chargedAmount: { type: DataTypes.FLOAT },
    finalPaidAmount: { type: DataTypes.FLOAT },
    payInChargedAmount: { type: DataTypes.FLOAT },
    paymentSource: { type: DataTypes.STRING },
    payOutChargedAmount: { type: DataTypes.FLOAT },
    totalGateWayAmount: { type: DataTypes.FLOAT },
    actualAmount: { type: DataTypes.FLOAT },
    customerName: { type: DataTypes.STRING },
    customerMobileNumber: { type: DataTypes.STRING },
    billerId: { type: DataTypes.STRING },
    transactionTime: { type: DataTypes.STRING },
    transactionDate: { type: DataTypes.STRING },
    academicYear: { type: DataTypes.STRING },

    payInProcessingFee: { type: DataTypes.FLOAT },
    payInProcessingPercentage: { type: DataTypes.FLOAT },

    payOutProcessingFee: { type: DataTypes.FLOAT },
    payOutProcessingPercentage: { type: DataTypes.FLOAT },

    commissionFee: { type: DataTypes.FLOAT },
    commissionPercentage: { type: DataTypes.FLOAT },
    mobileNumber: { type: DataTypes.STRING },
    bbpsServiceNumber: { type: DataTypes.STRING },
    bbpsTransactionId: { type: DataTypes.STRING },
    bbpsRequestId: { type: DataTypes.STRING },
    billerLogo: { type: DataTypes.STRING },
    MerchantId: { type: DataTypes.STRING },
    paymentMethod: { type: DataTypes.STRING },
    paymentType: { type: DataTypes.STRING },
    walletUpdatedBalance: { type: DataTypes.FLOAT },
    walletPreviousBalance: { type: DataTypes.FLOAT },
    finalPayableAmount: { type: DataTypes.FLOAT },
    payInRequired: { type: DataTypes.STRING },
    walletSettlementRequired: { type: DataTypes.STRING },
    payOutStatus: { type: DataTypes.STRING },
    transactionType: { type: DataTypes.STRING },
    payOutTransactionId: { type: DataTypes.STRING },
    payOutUTRNo: { type: DataTypes.STRING },
    payoutReferenceId: { type: DataTypes.STRING },
    contactType: { type: DataTypes.STRING },
    subOperator: { type: DataTypes.STRING },
    payOutInitiatedTime: { type: DataTypes.STRING },
    payOutInitiatedDate: { type: DataTypes.STRING },
    payOutPendingStateTime: { type: DataTypes.STRING },
    payOutPendingStateDate: { type: DataTypes.STRING },
    payOutSettledTime: { type: DataTypes.STRING },
    payOutSettledDate: { type: DataTypes.STRING },
    paymentMode: { type: DataTypes.STRING },
    billType: { type: DataTypes.STRING },
    detailsToSend: { type: DataTypes.JSONB }, // Object in Mongo → JSONB in PostgreSQL
    walletAmount: { type: DataTypes.FLOAT },
    walletAmountWithoutCharges: { type: DataTypes.FLOAT },
    serviceFirstParameterKey: { type: DataTypes.STRING },
    serviceFirstParameterValue: { type: DataTypes.STRING },
    serviceSecondParameterKey: { type: DataTypes.STRING },
    serviceSecondParameterValue: { type: DataTypes.STRING },
    creditCardNumber: { type: DataTypes.STRING },
    creditCardType: { type: DataTypes.STRING },
    bankCode: { type: DataTypes.STRING },
    bankName: { type: DataTypes.STRING },
    failuerReason: { type: DataTypes.STRING },
    failureMessage: { type: DataTypes.STRING },
    latitude: { type: DataTypes.STRING },
    longitude: { type: DataTypes.STRING },
    ipAddress: { type: DataTypes.STRING },
    activeService: { type: DataTypes.STRING },
  });

  return BbpsTransaction;
};
